export const data1 = {
  uuid: "WhFspqKJ",
  last_login_time: 1660817615626,
  channel: "uWhFspqKJztXfKlNI6M4zvB9yTqUjlyF",
  token: "rKlbiKVH39WxhOd2nEGJbPgSux4axUyF1NEtFWrajEiLFvhXIwNTpMz0qdX6mmqC",
  status: 1,
  email: "wangxueying@ones.ai",
  user_name: "8.28",
  user: {
    uuid: "WhFspqKJ",
    email: "wangxueying@ones.ai",
    name: "8.28",
    name_pinyin: "8.28",
    title: "",
    avatar: "",
    phone: "",
    create_time: 1615521868300539,
    status: 1,
    channel: "uWhFspqKJztXfKlNI6M4zvB9yTqUjlyF",
    token: "rKlbiKVH39WxhOd2nEGJbPgSux4axUyF1NEtFWrajEiLFvhXIwNTpMz0qdX6mmqC",
    license_types: [3, 5, 8, 9, 10, 12, 1, 4, 11, 13, 2],
    imported_jira_user: false,
    is_init_password: false,
    language: "zh",
  },
  teams: [
    {
      uuid: "PcR7h253",
      status: 1,
      name: "123",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1642392455444780,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 2,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "3FpEFWEF",
      status: 1,
      name: "A可口可乐",
      owner: "PEoin1MG",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1597823048602176,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 16,
      pending_member_count: 4,
      disable_member_count: 1,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu"],
      workhours: 500000,
      workhours_unit: "hour",
    },
    {
      uuid: "R7LMa95A",
      status: 1,
      name: "测试新建团队",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1616469220779200,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 3,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "J1ss17ed",
      status: 1,
      name: "cjk",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1635749407477872,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 4,
      pending_member_count: 1,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "FERq3JK2",
      status: 1,
      name: "core",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1603878874935808,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 5,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu"],
      workhours: 500000,
      workhours_unit: "hour",
    },
    {
      uuid: "8CwcWhpq",
      status: 1,
      name: "改名字",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1610345438524160,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 3,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "day",
    },
    {
      uuid: "4sBkCUHe",
      status: 1,
      name: "giaogiao2",
      owner: "3j4LZkLR",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1644393072417732,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "PRsWybQH",
      status: 1,
      name: "giaogiao4",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1644394061052539,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "GbyV3oun",
      status: 1,
      name: "工作项类型属性判断",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1621915096799408,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "78uPxzsL",
      status: 1,
      name: "hexiangtest12",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1644397381520911,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 7,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "QAX2Dyj7",
      status: 1,
      name: "hexiangtest13",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1644401316383327,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "88PNTstA",
      status: 1,
      name: "hexiang 12",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1644401925314556,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "NvdUSX8H",
      status: 1,
      name: "hosea 测试",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1642667478926027,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "H5Nq6uf6",
      status: 1,
      name: "吉吉加",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1607342886845552,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 13,
      pending_member_count: 0,
      disable_member_count: 1,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu"],
      workhours: 500000,
      workhours_unit: "hour",
    },
    {
      uuid: "3S2sxa2J",
      status: 1,
      name: "lo",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1641454548686394,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "8arVK4Lx",
      status: 1,
      name: "OPEN-TEST 专用（勿动）",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1658381311113254,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 2,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "2cTXBq2L",
      status: 1,
      name: "p1",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1618829111035376,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "G1GFxjhP",
      status: 1,
      name: "p2",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1621850703741600,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "UFrK1s12",
      status: 1,
      name: "P3020",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1609904992224208,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 2,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "V44Boggp",
      status: 1,
      name: "P8074",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1658906005615306,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "Aa887tpw",
      status: 1,
      name: "PPP3024(勿动)",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1619323058785248,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 9,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "Qxo26qqS",
      status: 1,
      name: "PublicShow",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1642498455081744,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "jknxJGXH",
      status: 1,
      name: "ROAR",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1615521868299920,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 15,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "TJkfgA3T",
      status: 1,
      name: "四喜丸子",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1639540833877246,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "41NfHmBD",
      status: 1,
      name: "t1",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1641889801856500,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "NNNMTg2X",
      status: 1,
      name: "test",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1641452012301433,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "2VykJiMu",
      status: 1,
      name: "test",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1641454031621227,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "XZbAfgkN",
      status: 1,
      name: "test0214",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1644812442077013,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "ByZSsLU6",
      status: 1,
      name: "test11111",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1645168146491658,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "Hi8hxLpf",
      status: 1,
      name: "Tony Test",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1637549029520560,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "GL3cVbw8",
      status: 1,
      name: "ttttttt",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1621841978656480,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 2,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "MaLkNh4m",
      status: 1,
      name: "wd test",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1645179534919391,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "5BszqBQo",
      status: 1,
      name: "wogiao",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1641874426141131,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 3,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "HaJ6exgk",
      status: 1,
      name: "伍健专用01（勿动）",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1604461257265120,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 3,
      pending_member_count: 1,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu"],
      workhours: 500000,
      workhours_unit: "hour",
    },
    {
      uuid: "4ZRQKfoJ",
      status: 1,
      name: "新团队01",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1640677535457727,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 17,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "Uu1AeJAR",
      status: 1,
      name: "yyyy",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1641874717889439,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 1,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
    {
      uuid: "ThBQP6dN",
      status: 1,
      name: "zzzz",
      owner: "WhFspqKJ",
      logo: "",
      cover_url: "",
      domain: "",
      create_time: 1660124891550450,
      expire_time: -1,
      type: "pro",
      config: {
        sprint: {
          alias: "",
        },
      },
      member_count: 1,
      pending_member_count: 0,
      disable_member_count: 0,
      org_uuid: "JGpj1YSe",
      workdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      workhours: 800000,
      workhours_unit: "hour",
    },
  ],
  org: {
    org_type: 0,
    uuid: "JGpj1YSe",
    name: "TESTyaya1",
    style_hash: "",
    favicon: "",
    notifications: [],
    status: 1,
    visibility: true,
  },
  license_types: [3, 5, 8, 9, 10, 12, 1, 4, 11, 13, 2],
  phone: "",
};

export const data2 = {
  id: "123",
  author: {
    id: "1",
    name: "Paul",
  },
  title: "My awesome blog post",
  comments: [
    {
      id: "324",
      commenter: {
        id: "2",
        name: "Nicole",
      },
    },
  ],
};

export const data3 = {
  "sidebar-menus": [
    {
      uuid: "ErK5QiHe",
      key: "team_setting",
      default_value: "团队配置中心",
      value: "团队配置中心",
      element_show: false,
      is_show: false,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 0,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
    {
      uuid: "PBwb3sNB",
      key: "project_setting",
      default_value: "Project 配置中心",
      value: "Project 配置中心",
      element_show: true,
      is_show: true,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 1,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
    {
      uuid: "Kf4eHqsv",
      key: "wiki_setting",
      default_value: "Wiki 配置中心",
      value: "Wiki 配置中心",
      element_show: true,
      is_show: true,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 2,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
    {
      uuid: "QEPhLK3z",
      key: "testcase_setting",
      default_value: "TestCase 配置中心",
      value: "TestCase 配置中心",
      element_show: true,
      is_show: true,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 3,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
    {
      uuid: "MQwqzTsT",
      key: "pipeline_setting",
      default_value: "Pipeline 配置中心",
      value: "Pipeline 配置中心",
      element_show: true,
      is_show: true,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 4,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
    {
      uuid: "BZ5w21gc",
      key: "plan_setting",
      default_value: "Plan 配置中心",
      value: "Plan 配置中心",
      element_show: true,
      is_show: true,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 5,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
    {
      uuid: "PsnJqQCR",
      key: "performance_setting",
      default_value: "Performance 配置中心",
      value: "效能管理配置中心",
      element_show: true,
      is_show: true,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 6,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
    {
      uuid: "5M8NVJkW",
      key: "automation_setting",
      default_value: "Automation 配置中心",
      value: "流程自动化配置",
      element_show: true,
      is_show: true,
      is_can_update_text: true,
      is_can_update_is_show: false,
      position: 7,
      category: "config_center",
      parent_uuid: "",
      is_directory: false,
      ext: null,
      user_domains: [],
    },
  ],
  "custom-sidebar-menus": [],
};
